package com.gilpereda.aoc2025.day07

import com.gilpereda.aoc2025.BaseTest
import com.gilpereda.aoc2025.Executable

class DayTest : BaseTest() {
    override val example: String =
        """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """.trimIndent()

    override val resultExample1: String = "21"

    override val resultReal1: String = "1581"

    override val resultExample2: String = "40"

    override val resultReal2: String = "73007003089792"

    override val input: String = "/day07/input"

    override val run1: Executable = ::firstTask

    override val run2: Executable = ::secondTask
}
